//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K3Log.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\n5tm\\\\Documents\\N5TM_DB\\N5TM_Full_NextGen.SQLite")]
        public string SQLiteFile {
            get {
                return ((string)(this["SQLiteFile"]));
            }
            set {
                this["SQLiteFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K3")]
        public string Rig {
            get {
                return ((string)(this["Rig"]));
            }
            set {
                this["Rig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N5TM")]
        public string MyCall {
            get {
                return ((string)(this["MyCall"]));
            }
            set {
                this["MyCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EL29ds")]
        public string MyGrid {
            get {
                return ((string)(this["MyGrid"]));
            }
            set {
                this["MyGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Com2")]
        public string Port {
            get {
                return ((string)(this["Port"]));
            }
            set {
                this["Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38400")]
        public int Baud {
            get {
                return ((int)(this["Baud"]));
            }
            set {
                this["Baud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string Rig2 {
            get {
                return ((string)(this["Rig2"]));
            }
            set {
                this["Rig2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7133986432@tmomail.net")]
        public string SMSNumber {
            get {
                return ((string)(this["SMSNumber"]));
            }
            set {
                this["SMSNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EL29;EM20")]
        public string NoCallGrids {
            get {
                return ((string)(this["NoCallGrids"]));
            }
            set {
                this["NoCallGrids"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\n5tm\\\\Documents\\\\N5TM_DB\\\\country.xml")]
        public string CountryList {
            get {
                return ((string)(this["CountryList"]));
            }
            set {
                this["CountryList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\n5tm\\\\Documents\\\\N5TM_DB\\\\bandplan_r2.xml")]
        public string BandPlan {
            get {
                return ((string)(this["BandPlan"]));
            }
            set {
                this["BandPlan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n5tm")]
        public string QRZLogin {
            get {
                return ((string)(this["QRZLogin"]));
            }
            set {
                this["QRZLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dange123")]
        public string QRZPwd {
            get {
                return ((string)(this["QRZPwd"]));
            }
            set {
                this["QRZPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color WorkedGridColor {
            get {
                return ((global::System.Drawing.Color)(this["WorkedGridColor"]));
            }
            set {
                this["WorkedGridColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 0")]
        public global::System.Drawing.Color InitalSpotColor {
            get {
                return ((global::System.Drawing.Color)(this["InitalSpotColor"]));
            }
            set {
                this["InitalSpotColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color BoundaryColor {
            get {
                return ((global::System.Drawing.Color)(this["BoundaryColor"]));
            }
            set {
                this["BoundaryColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color WorkedSpotColor {
            get {
                return ((global::System.Drawing.Color)(this["WorkedSpotColor"]));
            }
            set {
                this["WorkedSpotColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color NewGridColor {
            get {
                return ((global::System.Drawing.Color)(this["NewGridColor"]));
            }
            set {
                this["NewGridColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CL59")]
        public string LowerLeftGrid {
            get {
                return ((string)(this["LowerLeftGrid"]));
            }
            set {
                this["LowerLeftGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FN95")]
        public string UpperRightGrid {
            get {
                return ((string)(this["UpperRightGrid"]));
            }
            set {
                this["UpperRightGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dan")]
        public string MyName {
            get {
                return ((string)(this["MyName"]));
            }
            set {
                this["MyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WKeyer {
            get {
                return ((bool)(this["WKeyer"]));
            }
            set {
                this["WKeyer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WKSidetone {
            get {
                return ((bool)(this["WKSidetone"]));
            }
            set {
                this["WKSidetone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte WKSToneFreq {
            get {
                return ((byte)(this["WKSToneFreq"]));
            }
            set {
                this["WKSToneFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WKRevPdl {
            get {
                return ((bool)(this["WKRevPdl"]));
            }
            set {
                this["WKRevPdl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte WKPdlMode {
            get {
                return ((byte)(this["WKPdlMode"]));
            }
            set {
                this["WKPdlMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM5")]
        public string WKComport {
            get {
                return ((string)(this["WKComport"]));
            }
            set {
                this["WKComport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WKCTSpace {
            get {
                return ((bool)(this["WKCTSpace"]));
            }
            set {
                this["WKCTSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WKAutoSpace {
            get {
                return ((bool)(this["WKAutoSpace"]));
            }
            set {
                this["WKAutoSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Harris")]
        public string MyCnty {
            get {
                return ((string)(this["MyCnty"]));
            }
            set {
                this["MyCnty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NA")]
        public string MyContinent {
            get {
                return ((string)(this["MyContinent"]));
            }
            set {
                this["MyContinent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MyCQZone {
            get {
                return ((int)(this["MyCQZone"]));
            }
            set {
                this["MyCQZone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int MyITUZone {
            get {
                return ((int)(this["MyITUZone"]));
            }
            set {
                this["MyITUZone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("291")]
        public int MyDXCC {
            get {
                return ((int)(this["MyDXCC"]));
            }
            set {
                this["MyDXCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::K3Log.SatelliteCollection Satellites {
            get {
                return ((global::K3Log.SatelliteCollection)(this["Satellites"]));
            }
            set {
                this["Satellites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::K3Log.BandPowerCollection BandPower {
            get {
                return ((global::K3Log.BandPowerCollection)(this["BandPower"]));
            }
            set {
                this["BandPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM15")]
        public string VirtualPort {
            get {
                return ((string)(this["VirtualPort"]));
            }
            set {
                this["VirtualPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38400")]
        public int VirtualBaud {
            get {
                return ((int)(this["VirtualBaud"]));
            }
            set {
                this["VirtualBaud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte WKOutport {
            get {
                return ((byte)(this["WKOutport"]));
            }
            set {
                this["WKOutport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoTW {
            get {
                return ((string)(this["LoTW"]));
            }
            set {
                this["LoTW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM14")]
        public string Alt1Port {
            get {
                return ((string)(this["Alt1Port"]));
            }
            set {
                this["Alt1Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM19")]
        public string Alt2Port {
            get {
                return ((string)(this["Alt2Port"]));
            }
            set {
                this["Alt2Port"] = value;
            }
        }
    }
}
